# Use the official Node.js image
FROM node:18-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install --frozen-lockfile

# Copy the rest of the application files
COPY . .

# Expose the port the app will run on
EXPOSE 5173

# Run the frontend app
CMD ["npm", "run", "dev","--","--host", "0.0.0.0"]
