# Use Node.js 18 with Alpine
FROM node:18-alpine

# Install necessary dependencies for bcrypt
RUN apk add --no-cache python3 g++ make

# Set working directory
WORKDIR /app

# Copy only package.json first to leverage Docker caching
COPY src/package*.json /app/

# Install dependencies inside the container
RUN npm install --build-from-source bcrypt
RUN npm install multer



# Copy the rest of the application
COPY . .

# Set user permissions
RUN adduser -D appuser && \
    chown -R appuser:appuser /app
USER appuser

# Expose port
EXPOSE 3000

# Healthcheck
HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl --fail http://localhost:3000/health || exit 1

# Start application
CMD ["node", "src/index.js"]
