# Utilizamos una imagen base oficial de Node.js
FROM node:18

# Establecemos el directorio de trabajo en el contenedor
WORKDIR /src

# Copiamos los archivos de package.json y package-lock.json
COPY src/package*.json ./

# Instalamos las dependencias necesarias
RUN npm install

# Copiamos el resto de los archivos de la aplicación
COPY src/. .

# Exponemos el puerto en el que se ejecutará el backend
EXPOSE 3000

# Comando por defecto para iniciar la aplicación
CMD ["npm", "start"]
