# Utilizamos una imagen base oficial de Node.js
FROM node:18-alpine

# Establecemos el directorio de trabajo en el contenedor
WORKDIR /app

# Copiamos los archivos de package.json y package-lock.json
COPY src/package*.json /app/

# Instalamos las dependencias necesarias
RUN npm install

# Copiamos el resto de los archivos de la aplicación
COPY . .

# Establecemos el usuario y grupo del contenedor
RUN adduser -D appuser && \
    chown -R appuser:appuser /app
USER appuser
# Exponemos el puerto en el que se ejecutará el backend
EXPOSE 3000
# Comando para verificar la salud del backend
HEALTHCHECK --interval=30s --timeout=3s \
    CMD curl --fail http://localhost:3000/health || exit 1
# Comando por defecto para iniciar la aplicación
CMD ["node", "src/index.js"]
